/**
 * double_pendulum_node.cpp
 * ------------------------
 * ROS2 node implementing double pendulum dynamics generated by MechanicsDSL.
 *
 * DSL specification:
 *   \system{double_pendulum}
 *   \parameter{m}{1.0}{kg}
 *   \parameter{l}{1.0}{m}
 *   \lagrangian{
 *       0.5*m*l^2*(2*\dot{theta1}^2 + \dot{theta2}^2
 *                  + 2*\dot{theta1}*\dot{theta2}*cos(theta1-theta2))
 *       + m*g*l*(2*cos(theta1) + cos(theta2))
 *   }
 *   \target{ros2}
 *
 * Published topics:
 *   /double_pendulum/state   [mechanicsdsl_pendulum/SystemState]  200 Hz
 *
 * Author: MechanicsDSL (github.com/MechanicsDSL)
 * License: MIT
 */

#include <cmath>
#include <chrono>
#include <memory>
#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/bool.hpp"
#include "mechanicsdsl_pendulum/msg/system_state.hpp"

using namespace std::chrono_literals;
using SystemState = mechanicsdsl_pendulum::msg::SystemState;

// ---------------------------------------------------------------------------
// MechanicsDSL-generated EOM
// ---------------------------------------------------------------------------
static void dp_eom(double th1, double th2, double w1, double w2,
                   double g, double l,
                   double& dth1, double& dth2, double& dw1, double& dw2) {
    const double delta = th1 - th2;
    const double cd = std::cos(delta), sd = std::sin(delta);
    const double den = l * (2.0 - cd*cd);
    dth1 = w1; dth2 = w2;
    dw1 = ((-g*2.0*std::sin(th1)) - sd*(w2*w2*l + w1*w1*l*cd)) / den;
    dw2 = (sd*(2.0*w1*w1*l + g*std::cos(th1) + w2*w2*l*cd)) / den;
}

static double dp_hamiltonian(double th1, double th2, double w1, double w2,
                              double m, double l, double g) {
    const double T = 0.5*m*l*l*(2*w1*w1 + w2*w2 + 2*w1*w2*std::cos(th1-th2));
    const double V = -m*g*l*(2*std::cos(th1) + std::cos(th2));
    return T + V;
}

static void rk4_step(double& th1, double& th2, double& w1, double& w2,
                     double dt, double g, double l) {
    double k1_th1,k1_th2,k1_w1,k1_w2, k2_th1,k2_th2,k2_w1,k2_w2,
           k3_th1,k3_th2,k3_w1,k3_w2, k4_th1,k4_th2,k4_w1,k4_w2;
    dp_eom(th1,th2,w1,w2,g,l, k1_th1,k1_th2,k1_w1,k1_w2);
    dp_eom(th1+.5*dt*k1_th1,th2+.5*dt*k1_th2,w1+.5*dt*k1_w1,w2+.5*dt*k1_w2,g,l, k2_th1,k2_th2,k2_w1,k2_w2);
    dp_eom(th1+.5*dt*k2_th1,th2+.5*dt*k2_th2,w1+.5*dt*k2_w1,w2+.5*dt*k2_w2,g,l, k3_th1,k3_th2,k3_w1,k3_w2);
    dp_eom(th1+dt*k3_th1,th2+dt*k3_th2,w1+dt*k3_w1,w2+dt*k3_w2,g,l, k4_th1,k4_th2,k4_w1,k4_w2);
    th1 += (dt/6.)*(k1_th1+2*k2_th1+2*k3_th1+k4_th1);
    th2 += (dt/6.)*(k1_th2+2*k2_th2+2*k3_th2+k4_th2);
    w1  += (dt/6.)*(k1_w1 +2*k2_w1 +2*k3_w1 +k4_w1);
    w2  += (dt/6.)*(k1_w2 +2*k2_w2 +2*k3_w2 +k4_w2);
}

// ---------------------------------------------------------------------------
// DoublePendulumNode
// ---------------------------------------------------------------------------
class DoublePendulumNode : public rclcpp::Node {
public:
    DoublePendulumNode() : Node("double_pendulum_node") {
        this->declare_parameter("m_kg",    1.0);
        this->declare_parameter("l_m",     1.0);
        this->declare_parameter("g_mps2",  9.81);
        this->declare_parameter("theta1_0",0.8);
        this->declare_parameter("theta2_0",0.4);
        this->declare_parameter("dt_s",    0.005);
        this->declare_parameter("drift_tol",1e-3);

        m_  = this->get_parameter("m_kg").as_double();
        l_  = this->get_parameter("l_m").as_double();
        g_  = this->get_parameter("g_mps2").as_double();
        th1_= this->get_parameter("theta1_0").as_double();
        th2_= this->get_parameter("theta2_0").as_double();
        dt_ = this->get_parameter("dt_s").as_double();
        tol_= this->get_parameter("drift_tol").as_double();
        w1_=0; w2_=0; t_=0;
        E0_ = dp_hamiltonian(th1_,th2_,w1_,w2_,m_,l_,g_);

        pub_ = this->create_publisher<SystemState>("/double_pendulum/state",
                rclcpp::SensorDataQoS());

        sub_reset_ = this->create_subscription<std_msgs::msg::Bool>(
            "/double_pendulum/reset", 10,
            [this](const std_msgs::msg::Bool::SharedPtr) { reset(); });

        const auto period = std::chrono::duration<double>(dt_);
        timer_ = this->create_wall_timer(
            std::chrono::duration_cast<std::chrono::nanoseconds>(period),
            std::bind(&DoublePendulumNode::tick, this));

        RCLCPP_INFO(this->get_logger(),
            "MechanicsDSL DoublePendulumNode: m=%.2f l=%.2f dt=%.4f", m_,l_,dt_);
    }

private:
    void reset() {
        th1_=this->get_parameter("theta1_0").as_double();
        th2_=this->get_parameter("theta2_0").as_double();
        w1_=0; w2_=0; t_=0;
        E0_=dp_hamiltonian(th1_,th2_,w1_,w2_,m_,l_,g_);
    }

    void tick() {
        rk4_step(th1_,th2_,w1_,w2_,dt_,g_,l_);
        t_ += dt_;
        const double E = dp_hamiltonian(th1_,th2_,w1_,w2_,m_,l_,g_);
        const double drift = std::abs((E-E0_)/E0_);
        if (drift > tol_)
            RCLCPP_WARN_THROTTLE(this->get_logger(),*this->get_clock(),1000,
                "Energy drift %.2e", drift);

        auto msg = SystemState();
        msg.header.stamp = this->now();
        msg.header.frame_id = "world";
        msg.q     = {th1_, th2_};
        msg.q_dot = {w1_,  w2_};
        msg.energy       = E;
        msg.energy_drift = drift;
        msg.sim_time     = t_;
        msg.conserved_quantities = {"energy"};
        pub_->publish(msg);
    }

    double m_,l_,g_,dt_,tol_,th1_,th2_,w1_,w2_,t_,E0_;
    rclcpp::Publisher<SystemState>::SharedPtr pub_;
    rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr sub_reset_;
    rclcpp::TimerBase::SharedPtr timer_;
};

int main(int argc, char** argv) {
    rclcpp::init(argc, argv);
    rclcpp::spin(std::make_shared<DoublePendulumNode>());
    rclcpp::shutdown();
    return 0;
}
