/**
 * pendulum_node.cpp
 * -----------------
 * ROS2 node implementing simple pendulum dynamics generated by MechanicsDSL.
 *
 * DSL specification:
 *   \system{pendulum}
 *   \parameter{m}{1.0}{kg}
 *   \parameter{l}{0.25}{m}
 *   \lagrangian{0.5*m*l^2*\dot{theta}^2 - m*g*l*(1-cos(theta))}
 *   \target{ros2}
 *
 * Published topics:
 *   /pendulum/state          [mechanicsdsl_pendulum/PendulumState]  250 Hz
 *   /pendulum/energy         [std_msgs/Float64]                     250 Hz
 *
 * Subscribed topics:
 *   /pendulum/reset          [std_msgs/Bool]      Reset to initial conditions
 *   /pendulum/set_params     [geometry_msgs/Vector3]  [m, l, g] update
 *
 * Parameters (ROS2 parameter server):
 *   m_kg       (double, default 1.0)   Pendulum mass [kg]
 *   l_m        (double, default 0.25)  Rod length [m]
 *   g_mps2     (double, default 9.81)  Gravitational acceleration [m/s^2]
 *   theta0_rad (double, default 0.30)  Initial angle [rad]
 *   dt_s       (double, default 0.004) Integration timestep [s]
 *   drift_tol  (double, default 1e-4)  Energy drift warning threshold
 *
 * Author: MechanicsDSL (github.com/MechanicsDSL)
 * License: MIT
 */

#include <cmath>
#include <chrono>
#include <memory>
#include <string>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/bool.hpp"
#include "std_msgs/msg/float64.hpp"
#include "geometry_msgs/msg/vector3.hpp"
#include "mechanicsdsl_pendulum/msg/pendulum_state.hpp"

using namespace std::chrono_literals;
using PendulumState = mechanicsdsl_pendulum::msg::PendulumState;

// ---------------------------------------------------------------------------
// MechanicsDSL-generated: equations of motion
// Euler-Lagrange on L = 0.5*m*l^2*omega^2 - m*g*l*(1-cos(theta))
// ---------------------------------------------------------------------------
static inline double eom_domega(double theta, double /*omega*/,
                                double g, double l) {
    return -(g / l) * std::sin(theta);
}

// ---------------------------------------------------------------------------
// MechanicsDSL-generated: Hamiltonian (Noether conserved energy)
// ---------------------------------------------------------------------------
static inline double hamiltonian(double theta, double omega,
                                 double m, double l, double g) {
    const double T = 0.5 * m * l * l * omega * omega;
    const double V = m * g * l * (1.0 - std::cos(theta));
    return T + V;
}

// ---------------------------------------------------------------------------
// Runge-Kutta 4 step
// ---------------------------------------------------------------------------
static void rk4_step(double& theta, double& omega, double dt,
                     double g, double l) {
    const double k1_th = omega;
    const double k1_om = eom_domega(theta, omega, g, l);

    const double k2_th = omega + 0.5 * dt * k1_om;
    const double k2_om = eom_domega(theta + 0.5*dt*k1_th, k2_th, g, l);

    const double k3_th = omega + 0.5 * dt * k2_om;
    const double k3_om = eom_domega(theta + 0.5*dt*k2_th, k3_th, g, l);

    const double k4_th = omega + dt * k3_om;
    const double k4_om = eom_domega(theta + dt*k3_th, k4_th, g, l);

    theta += (dt / 6.0) * (k1_th + 2*k2_th + 2*k3_th + k4_th);
    omega += (dt / 6.0) * (k1_om + 2*k2_om + 2*k3_om + k4_om);
}

// ---------------------------------------------------------------------------
// PendulumNode
// ---------------------------------------------------------------------------
class PendulumNode : public rclcpp::Node {
public:
    PendulumNode() : Node("pendulum_node") {
        // Declare and get parameters
        this->declare_parameter("m_kg",       1.0);
        this->declare_parameter("l_m",        0.25);
        this->declare_parameter("g_mps2",     9.81);
        this->declare_parameter("theta0_rad", 0.30);
        this->declare_parameter("dt_s",       0.004);
        this->declare_parameter("drift_tol",  1e-4);

        m_      = this->get_parameter("m_kg").as_double();
        l_      = this->get_parameter("l_m").as_double();
        g_      = this->get_parameter("g_mps2").as_double();
        dt_     = this->get_parameter("dt_s").as_double();
        drift_tol_ = this->get_parameter("drift_tol").as_double();

        theta_  = this->get_parameter("theta0_rad").as_double();
        omega_  = 0.0;
        t_sim_  = 0.0;
        E0_     = hamiltonian(theta_, omega_, m_, l_, g_);

        // Publishers
        pub_state_  = this->create_publisher<PendulumState>(
            "/pendulum/state", rclcpp::SensorDataQoS());
        pub_energy_ = this->create_publisher<std_msgs::msg::Float64>(
            "/pendulum/energy", rclcpp::SensorDataQoS());

        // Subscriptions
        sub_reset_ = this->create_subscription<std_msgs::msg::Bool>(
            "/pendulum/reset", 10,
            [this](const std_msgs::msg::Bool::SharedPtr) { reset(); });

        sub_params_ = this->create_subscription<geometry_msgs::msg::Vector3>(
            "/pendulum/set_params", 10,
            [this](const geometry_msgs::msg::Vector3::SharedPtr msg) {
                m_ = msg->x; l_ = msg->y; g_ = msg->z;
                E0_ = hamiltonian(theta_, omega_, m_, l_, g_);
                RCLCPP_INFO(this->get_logger(),
                    "Parameters updated: m=%.3f l=%.3f g=%.4f", m_, l_, g_);
            });

        // Timer at dt_ interval
        const auto period = std::chrono::duration<double>(dt_);
        timer_ = this->create_wall_timer(
            std::chrono::duration_cast<std::chrono::nanoseconds>(period),
            std::bind(&PendulumNode::timer_callback, this));

        RCLCPP_INFO(this->get_logger(),
            "MechanicsDSL PendulumNode started. "
            "m=%.2f kg, l=%.3f m, g=%.4f m/s^2, dt=%.4f s",
            m_, l_, g_, dt_);
    }

private:
    void reset() {
        theta_ = this->get_parameter("theta0_rad").as_double();
        omega_ = 0.0;
        t_sim_ = 0.0;
        E0_    = hamiltonian(theta_, omega_, m_, l_, g_);
        RCLCPP_INFO(this->get_logger(), "State reset to initial conditions.");
    }

    void timer_callback() {
        // Integrate one RK4 step
        rk4_step(theta_, omega_, dt_, g_, l_);
        t_sim_ += dt_;

        // Noether energy monitor
        const double E     = hamiltonian(theta_, omega_, m_, l_, g_);
        const double drift = std::abs((E - E0_) / E0_);
        if (drift > drift_tol_) {
            RCLCPP_WARN_THROTTLE(this->get_logger(), *this->get_clock(), 1000,
                "Energy drift |dE/E0| = %.2e exceeds tolerance %.2e "
                "(Noether: time-translation symmetry)", drift, drift_tol_);
        }

        // Publish state
        auto state_msg = PendulumState();
        state_msg.header.stamp = this->now();
        state_msg.header.frame_id = "world";
        state_msg.theta        = theta_;
        state_msg.omega        = omega_;
        state_msg.energy       = E;
        state_msg.energy_drift = drift;
        pub_state_->publish(state_msg);

        // Publish energy scalar
        auto energy_msg = std_msgs::msg::Float64();
        energy_msg.data = E;
        pub_energy_->publish(energy_msg);
    }

    // Physical parameters
    double m_, l_, g_, dt_, drift_tol_;

    // Simulation state
    double theta_, omega_, t_sim_, E0_;

    // ROS2 interfaces
    rclcpp::Publisher<PendulumState>::SharedPtr          pub_state_;
    rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr pub_energy_;
    rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr sub_reset_;
    rclcpp::Subscription<geometry_msgs::msg::Vector3>::SharedPtr sub_params_;
    rclcpp::TimerBase::SharedPtr timer_;
};

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
int main(int argc, char* argv[]) {
    rclcpp::init(argc, argv);
    rclcpp::spin(std::make_shared<PendulumNode>());
    rclcpp::shutdown();
    return 0;
}
